server:
  port: 9527

spring:
  application:
    name: cloud-gateway

    ##############################新增网关配置######################################
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开始从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh       #路由id
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getPaymentById/**     #断言，路径匹配的进行路由
            #- Cookie=chocolate,chip

    ###############################################################################

eureka:
  instance:
    instance-id: gateway9527
    hostname: cloud-gateway-service
  client:
    #表示是否将自己注册EurekaServer
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
